version: 0.2

phases:
  install:
    commands:
      - curl -O https://download.visualstudio.microsoft.com/download/pr/f5c74056-330b-452b-915e-d98fda75024e/18076ca3b89cd362162bbd0cbf9b2ca5/dotnet-sdk-7.0.100-rc.2.22477.23-linux-x64.tar.gz
      - sudo tar -zxvf dotnet-sdk-7.0.100-rc.2.22477.23-linux-x64.tar.gz -C /root/.dotnet
      - echo Restore started on `date`
      - dotnet restore trocitos.csproj
      
  build:
    commands:
      - dotnet build
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output

artifacts:
  files:
    - 'build_output/**/*'
  base-directory: './build_output'
  
  