version: 0.2

phases:
  install:
    commands:
      - curl -O https://download.visualstudio.microsoft.com/download/pr/dd7d2255-c9c1-4c6f-b8ad-6e853d6bb574/c8e1b5f47bf17b317a84487491915178/dotnet-sdk-6.0.408-linux-x64.tar.gz
      - dotnet tool install --global trx2junit
      - sudo tar -zxvf dotnet-sdk-6.0.408-linux-x64.tar.gz -C /root/.dotnet
      - echo Restore started on `date`
      - dotnet restore trocitos.mvc/trocitos.csproj
      
  build:
    commands:
      - dotnet build trocitos.mvc/trocitos.csproj
      - echo Build started on `date`
      - dotnet test trocitos.test/TrocitosTest.csproj --logger "trx;LogFileName=test_results.xml"
      - dotnet publish trocitos.mvc/trocitos.csproj -c release -o ./build_output
      - trx2junit TestResults.trx
  
artifacts:
  files:
    - '**/*'
  base-directory: './build_output'

reports: 
  dotnetTests:
    files:
    - '**/*.xml'
    file-format: JUNITXML
    base-directory: './trocitos.test/TestResults'
  
  