version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 7
    commands:
      - echo Restore started on `date`
      - dotnet restore

  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output

artifacts:
  files:
    - './build_output/**/*'
  base-directory: './build_output/'