version: 0.2

phases:
  install:
    commands:
      - curl -O https://download.visualstudio.microsoft.com/download/pr/1b0ca65c-c3b6-45d2-bc39-8597fe764364/1ce0bf0839b989ad8e8fb371ad720e25/dotnet-sdk-6.0.408-linux-x64.tar.gz
      - sudo tar -zxvf dotnet-sdk-6.0.408-linux-x64.tar.gz -C /root/.dotnet
      - echo Restore started on `date`
      - dotnet restore trocitos.csproj
      
  build:
    commands:
      - dotnet build
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output

artifacts:
  files:
    - '**/*'
  
  base-directory: 'build_output'

  
  